server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    gzip on;
    gzip_types text/html text/css application/javascript image/svg+xml;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "public, max-age=3600";
    }

    # Autoriser les robots crawlers
    location = /robots.txt {
        add_header Content-Type text/plain;
        return 200 "User-agent: *\nAllow: /\n";
    }

    # Health check pour le proxy nginx
    location = /health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 'ok';
    }
}
